[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.validate]
dependencies = [
    "format",
    "build",
    "test",
    "clippy",
]

[tasks.server]
command = "cargo"
args = ["run", "--bin", "server", "--", "--bind-address", "127.0.0.1:9999"]

[tasks.watch]
command = "cargo"
args = ["run", "--bin", "server", "--", "--bind-address", "127.0.0.1:9999"]
watch = true

[tasks.cli]
command = "cargo"
args = ["run", "--bin", "cli", "${@}"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.build-docker]
script_runner = "@shell"
dependencies = ["build-release"]
script = '''
docker build . -t haihala/mos-6502-disassembler
'''

[tasks.bench]
command = "cargo"
args = ["bench"]

