[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.validate]
dependencies = [
    "format",
    "build",
    "test",
    "clippy",
]

[tasks.server]
command = "cargo"
args = ["run", "--bin", "server"]

[tasks.watch]
command = "cargo"
args = ["run", "--bin", "server"]
watch = true

[tasks.cli]
command = "cargo"
args = ["run", "--bin", "cli", "${@}"]
