name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo make build-docker

      - name: Start container
        run: docker run -d -p 9999:8080 haihala/mos-6502-disassembler:latest

      - name: Run checks
        run: cargo make validate

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: haihala/mos-6502-disassembler:latest
